Repository BobJool/Waiting-Reservation-Service, pull requests merged in 2024-12, with the labels that each got.

#2 Feat/payment create,search
  .github/workflows/run-test.yml
  common/build.gradle
  common/src/main/java/com/bobjool/common/exception/BobJoolException.java
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  common/src/main/java/com/bobjool/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/bobjool/common/infra/aspect/RoleCheckAspect.java
  common/src/main/java/com/bobjool/common/presentation/ApiResponse.java
  common/src/main/java/com/bobjool/common/presentation/PageResponse.java
  reservation/build.gradle
  reservation/http/payment.http
  reservation/src/main/generated/com/bobjool/reservation/domain/entity/QPayment.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/PaymentCreateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/PaymentResponse.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/PaymentSearchDto.java
  reservation/src/main/java/com/bobjool/reservation/application/exception/PaymentExceptionHandler.java
  reservation/src/main/java/com/bobjool/reservation/application/interfaces/PgClient.java
  reservation/src/main/java/com/bobjool/reservation/application/service/PaymentService.java
  reservation/src/main/java/com/bobjool/reservation/domain/entity/Payment.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/PaymentMethod.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/PaymentStatus.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/PgName.java
  reservation/src/main/java/com/bobjool/reservation/domain/repository/PaymentRepository.java
  reservation/src/main/java/com/bobjool/reservation/infra/aspect/RequestLoggingAspect.java
  reservation/src/main/java/com/bobjool/reservation/infra/client/PgClientImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/config/aop/AopConfig.java
  reservation/src/main/java/com/bobjool/reservation/infra/config/jpa/AuditorAwareImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/config/jpa/JpaAuditingConfig.java
  reservation/src/main/java/com/bobjool/reservation/infra/config/querydsl/QueryDslConfig.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/payment/PaymentRepositoryCustom.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/payment/PaymentRepositoryCustomImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/payment/PaymentRepositoryImpl.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/PaymentController.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/PaymentCreateReqDto.java
  reservation/src/test/java/com/bobjool/reservation/application/service/PaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/entity/PaymentTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/enums/PaymentMethodTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/enums/PaymentStatusTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/repository/PaymentRepositoryTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/PaymentControllerTest.java
  reservation/src/test/resources/application-test.yml
Labels: enhancement

#8 Feat/payment refund, updateStatus
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  reservation/http/payment.http
  reservation/src/main/java/com/bobjool/reservation/application/dto/PaymentUpdateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/service/PaymentService.java
  reservation/src/main/java/com/bobjool/reservation/domain/entity/Payment.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/PaymentController.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/PaymentUpdateReqDto.java
  reservation/src/main/resources/application-dev.yml
  reservation/src/test/java/com/bobjool/reservation/application/service/PaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/entity/PaymentTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/PaymentControllerTest.java
Labels: 기능

#10 Feat/payment-findOne
  reservation/http/payment.http
  reservation/src/main/java/com/bobjool/reservation/application/dto/PaymentResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/service/PaymentService.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/PaymentController.java
  reservation/src/test/java/com/bobjool/reservation/application/service/PaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/PaymentControllerTest.java
Labels: 기능

#14 Chore/notification
  notification/build.gradle
  notification/src/main/java/com/bobjool/notification/NotificationApplication.java
  notification/src/main/java/com/bobjool/notification/application/service/NotificationService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/Notification.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationCategory.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationChannel.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationStatus.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationType.java
  notification/src/main/java/com/bobjool/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/bobjool/notification/infrastructure/aspect/RequestLoggingAspect.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/aop/AopConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/jpa/AuditorAwareImpl.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/jpa/JpaAuditingConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/querydsl/QueryDslConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/NotificationRepositoryCustom.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/NotificationRepositoryCustomImpl.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/NotificationRepositoryImpl.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/NotificationController.java
  notification/src/main/resources/application-dev.yml
Labels: 설정

#11 Feat/config service
  config/src/main/resources/application-dev.yml
  config/src/main/resources/application.yml
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/notification-service.yml
  config/src/main/resources/config-repo/queue-service.yml
  config/src/main/resources/config-repo/restaurant-service.yml
  restaurant/build.gradle
  restaurant/src/main/resources/application-dev.yml
Labels: 설정

#17 [GitHub] chore: PR 템플릿 변경사항 반영 #16
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 설정

#19 Chore/ai
  notification/src/main/java/com/bobjool/notification/application/service/AiService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/Ai.java
  notification/src/main/java/com/bobjool/notification/domain/repository/AiRepository.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/AiRepositoryCustom.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/AiRepositoryCustomImpl.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/AiRepositoryImpl.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/AiController.java
Labels: 설정

#21 Chore/queue
  config/src/main/resources/config-repo/queue-service.yml
  queue/build.gradle
  queue/src/main/java/com/bobjool/queue/application/exception/QueueExceptionHandler.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/RequestLoggingAspect.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/aop/AopConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/jpa/AuditorAwareImpl.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/jpa/JpaAuditingConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/querydsl/QueryDslConfig.java
Labels: 설정
