Repository BobJool/Waiting-Reservation-Service, pull requests merged in 2025-01, with the labels that each got.

#29 Feat/reservation-create, updateStatus, cancle / Fix/common-GlobalExceptionHandler 에 JSON 형식 안 맞을 때 예외 처리
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  common/src/main/java/com/bobjool/common/exception/GlobalExceptionHandler.java
  reservation/http/reservation.http
  reservation/src/main/generated/com/bobjool/reservation/domain/entity/QReservation.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentCreateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentSearchDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentUpdateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationCreateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationUpdateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/service/PaymentService.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/domain/entity/Payment.java
  reservation/src/main/java/com/bobjool/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/ReservationStatus.java
  reservation/src/main/java/com/bobjool/reservation/domain/repository/PaymentRepository.java
  reservation/src/main/java/com/bobjool/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryCustom.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryCustomImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryImpl.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/PaymentController.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/payment/PaymentCreateReqDto.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/payment/PaymentUpdateReqDto.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/reservation/ReservationCreateReqDto.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/reservation/ReservationUpdateReqDto.java
  reservation/src/test/java/com/bobjool/reservation/application/service/PaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/entity/ReservationTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/enums/ReservationStatusTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/PaymentControllerTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java
  reservation/src/test/resources/application-test.yml
Labels: 버그, 기능

#32 [Reservation] feat: 예약 상세 조회 - #26
  reservation/http/reservation.http
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java
Labels: 기능

#36 [Reservation] feat: 예약 목록 조회 - #27
  reservation/http/reservation.http
  reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationSearchDto.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryCustom.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/reservation/ReservationRepositoryCustomImpl.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/repository/ReservationRepositoryTest.java
Labels: 기능

#38 Feat/restaurant create
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  restaurant/build.gradle
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/RestaurantCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/RestaurantResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/RestaurantUpdateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/exception/RestaurantExceptionHandler.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/RestaurantService.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/Restaurant.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/RestaurantCategory.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/RestaurantRegion.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/RestaurantSchedule.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/repository/RestaurantRepository.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/config/querydsl/JpaConfig.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/config/querydsl/QueryDslConfig.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/RestaurantRepositoryCustom.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/RestaurantRepositoryCustomImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/RestaurantRepositoryImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/RestaurantController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/RestaurantCreateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/RestaurantUpdateReqDto.java
Labels: 기능

#30 Feat/auth sign-in, sign-up api 개발
  auth/build.gradle
  auth/src/main/java/com/bobjool/application/dto/SignInDto.java
  auth/src/main/java/com/bobjool/application/dto/SignUpDto.java
  auth/src/main/java/com/bobjool/application/interfaces/JwtUtil.java
  auth/src/main/java/com/bobjool/application/service/AuthService.java
  auth/src/main/java/com/bobjool/application/service/JwtBlacklistService.java
  auth/src/main/java/com/bobjool/application/service/RedisService.java
  auth/src/main/java/com/bobjool/application/service/ValidationService.java
  auth/src/main/java/com/bobjool/domain/entity/User.java
  auth/src/main/java/com/bobjool/domain/entity/UserRole.java
  auth/src/main/java/com/bobjool/domain/repository/UserRepository.java
  auth/src/main/java/com/bobjool/infrastructure/config/RedisConfig.java
  auth/src/main/java/com/bobjool/infrastructure/repository/user/UserRepositoryImpl.java
  auth/src/main/java/com/bobjool/infrastructure/security/CustomUserDetailsImpl.java
  auth/src/main/java/com/bobjool/infrastructure/security/CustomUserDetailsServiceImpl.java
  auth/src/main/java/com/bobjool/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/java/com/bobjool/infrastructure/security/JwtUtilImpl.java
  auth/src/main/java/com/bobjool/infrastructure/security/WebSecurityConfig.java
  auth/src/main/java/com/bobjool/presentation/controller/AuthController.java
  auth/src/main/java/com/bobjool/presentation/dto/request/SignInReqDto.java
  auth/src/main/java/com/bobjool/presentation/dto/request/SignUpReqDto.java
  auth/src/main/java/com/bobjool/presentation/dto/response/SignInResDto.java
  auth/src/main/resources/application-dev.yml
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
Labels: 기능

#44 Feat/notification template-update, delete
  notification/http/template.http
  notification/src/main/java/com/bobjool/notification/application/service/TemplateService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationType.java
  notification/src/main/java/com/bobjool/notification/domain/entity/Template.java
  notification/src/main/java/com/bobjool/notification/domain/repository/TemplateRepository.java
  notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/TemplateController.java
  notification/src/main/java/com/bobjool/notification/presentation/response/TemplateDeleteResDto.java
  notification/src/main/java/com/bobjool/notification/presentation/response/TemplateSelectResDto.java
  notification/src/main/java/com/bobjool/notification/presentation/response/TemplateUpdateResDto.java
Labels: 기능

#47 [Notification] chore: Jackson SNAKE 명명법 설정 #44
  notification/src/main/resources/application-dev.yml
Labels: 설정

#49 Feat/queue register
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  common/src/main/java/com/bobjool/common/presentation/SuccessCode.java
  config/src/main/resources/config-repo/queue-service.yml
  queue/build.gradle
  queue/src/main/java/com/bobjool/queue/application/dto/QueueRegisterDto.java
  queue/src/main/java/com/bobjool/queue/application/dto/QueueRegisterResDto.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessageSubscriber.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisQueueService.java
  queue/src/main/java/com/bobjool/queue/domain/entity/Queue.java
  queue/src/main/java/com/bobjool/queue/domain/enums/DiningOption.java
  queue/src/main/java/com/bobjool/queue/domain/enums/QueueStatus.java
  queue/src/main/java/com/bobjool/queue/domain/enums/QueueType.java
  queue/src/main/java/com/bobjool/queue/domain/repository/QueueRepository.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisPubSubConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/repository/QueueRepositoryCustom.java
  queue/src/main/java/com/bobjool/queue/infrastructure/repository/QueueRepositoryCustomImpl.java
  queue/src/main/java/com/bobjool/queue/infrastructure/repository/QueueRepositoryImpl.java
  queue/src/main/java/com/bobjool/queue/presentation/controller/QueueController.java
  queue/src/main/java/com/bobjool/queue/presentation/dto/QueueRegisterReqDto.java
  queue/src/main/resources/application-dev.yml
  queue/src/test/java/com/bobjool/queue/presentation/controller/QueueControllerTest.java
  queue/src/test/resources/application-test.yml
Labels: 기능

#48 [Restaurant] Feat/restaurant schedule create #41
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantUpdateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleReserveDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleUpdateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurant/RestaurantService.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurantSchedule/RestaurantScheduleService.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/RestaurantSchedule.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurant/Restaurant.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurant/RestaurantCategory.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurant/RestaurantRegion.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurantSchedule/RestaurantSchedule.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/repository/RestaurantRepository.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/repository/RestaurantScheduleRepository.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurant/RestaurantRepositoryCustom.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurant/RestaurantRepositoryCustomImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurant/RestaurantRepositoryImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurantSchedule/RestaurantScheduleRepositoryCustom.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurantSchedule/RestaurantScheduleRepositoryCustomImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurantSchedule/RestaurantScheduleRepositoryImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/restaurant/RestaurantController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/restaurantSchedule/RestaurantScheduleController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurant/RestaurantCreateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurant/RestaurantUpdateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleCreateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleReserveReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleUpdateReqDto.java
Labels: 기능

#50 [Reservation] refactor/reservation - 예약 날짜, 시간 추가 #45
  reservation/http/reservation.http
  reservation/src/main/generated/com/bobjool/reservation/domain/entity/QReservation.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationCreateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/reservation/ReservationResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/reservation/ReservationCreateReqDto.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationPaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/entity/ReservationTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/repository/ReservationRepositoryTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/service/ReservationPaymentDomainServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java
Labels: 리팩토링

#52 [Auth] feat/auth - 로그아웃 기능 추가
  auth/src/main/java/com/bobjool/application/interfaces/JwtUtil.java
  auth/src/main/java/com/bobjool/application/service/AuthService.java
  auth/src/main/java/com/bobjool/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/java/com/bobjool/infrastructure/security/JwtUtilImpl.java
  auth/src/main/java/com/bobjool/presentation/controller/AuthController.java
  auth/src/main/java/com/bobjool/presentation/controller/UserController.java
  auth/src/test/java/com/bobjool/auth/application/service/AuthServiceTest.java
  auth/src/test/java/com/bobjool/auth/application/service/JwtBlacklistServiceTest.java
  auth/src/test/resources/application-test.yml
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
Labels: 기능

#59 Chore/restaurant schedule feedback daily schedule,create,update
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurant/RestaurantService.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurantSchedule/RestaurantScheduleService.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurantSchedule/RestaurantSchedule.java
Labels: 리팩토링

#67 Feat/queue-checkin
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  queue/src/main/java/com/bobjool/queue/application/dto/QueueCheckInDto.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessagePublisherService.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessageSubscriber.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisQueueService.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisPubSubConfig.java
  queue/src/main/java/com/bobjool/queue/presentation/controller/QueueController.java
Labels: 기능

#77 Feat/reservation - create - kafka
  config/src/main/resources/config-repo/reservation-service.yml
  docker-compose.yml
  gateway/src/main/resources/application-dev.yml
  payment/http/payment.http
  payment/src/main/java/com/bobjool/payment/presentation/controller/PaymentController.java
  payment/src/test/java/com/bobjool/payment/presentation/controller/PaymentControllerTest.java
  reservation/build.gradle
  reservation/http/payment.http
  reservation/src/main/generated/com/bobjool/reservation/domain/entity/QPayment.java
  reservation/src/main/java/com/bobjool/reservation/EventSerializer.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentCreateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentSearchDto.java
  reservation/src/main/java/com/bobjool/reservation/application/dto/payment/PaymentUpdateDto.java
  reservation/src/main/java/com/bobjool/reservation/application/events/ReservationCreatedEvent.java
  reservation/src/main/java/com/bobjool/reservation/application/interfaces/PgClient.java
  reservation/src/main/java/com/bobjool/reservation/application/service/PaymentService.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationPaymentService.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/domain/entity/Payment.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/PaymentMethod.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/PaymentStatus.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/PgName.java
  reservation/src/main/java/com/bobjool/reservation/domain/enums/ReservationTopic.java
  reservation/src/main/java/com/bobjool/reservation/domain/repository/PaymentRepository.java
  reservation/src/main/java/com/bobjool/reservation/domain/service/ReservationPaymentDomainService.java
  reservation/src/main/java/com/bobjool/reservation/infra/client/PgClientImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/kafka/ReservationProducer.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/payment/PaymentRepositoryCustom.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/payment/PaymentRepositoryCustomImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/repository/payment/PaymentRepositoryImpl.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/PaymentController.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/payment/PaymentCreateReqDto.java
  reservation/src/main/java/com/bobjool/reservation/presentation/dto/payment/PaymentUpdateReqDto.java
  reservation/src/test/java/com/bobjool/reservation/application/service/PaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationPaymentServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/entity/PaymentTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/enums/PaymentMethodTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/enums/PaymentStatusTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/enums/ReservationStatusTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/repository/PaymentRepositoryTest.java
  reservation/src/test/java/com/bobjool/reservation/domain/service/ReservationPaymentDomainServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/PaymentControllerTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java
Labels: 기능

#84 Feat/notification - 메시지 데이터 수집
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  notification/http/slack.http
  notification/http/template.http
  notification/src/main/java/com/bobjool/notification/application/client/RestaurantClient.java
  notification/src/main/java/com/bobjool/notification/application/client/UserClient.java
  notification/src/main/java/com/bobjool/notification/application/dto/ApiResponseDto.java
  notification/src/main/java/com/bobjool/notification/application/dto/NotificationDto.java
  notification/src/main/java/com/bobjool/notification/application/dto/RestaurantContactDto.java
  notification/src/main/java/com/bobjool/notification/application/dto/UserContactDto.java
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/application/service/NotificationService.java
  notification/src/main/java/com/bobjool/notification/application/service/TemplateService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/Notification.java
  notification/src/main/java/com/bobjool/notification/domain/entity/TemplateContactField.java
  notification/src/main/java/com/bobjool/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java
  notification/src/main/java/com/bobjool/notification/infrastructure/client/RestaurantClientImpl.java
  notification/src/main/java/com/bobjool/notification/infrastructure/client/UserClientImpl.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/AiRepositoryImpl.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/NotificationController.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/SlackController.java
  notification/src/main/java/com/bobjool/notification/presentation/request/NotificationReqDto.java
Labels: 기능

#85 Feat/queue alert
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  queue/src/main/java/com/bobjool/queue/application/dto/QueueAlertDto.java
  queue/src/main/java/com/bobjool/queue/application/dto/QueueCancelDto.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessagePublisherService.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessageSubscriber.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisExpirationListener.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisQueueService.java
  queue/src/main/java/com/bobjool/queue/domain/enums/CancelType.java
  queue/src/main/java/com/bobjool/queue/domain/enums/QueueStatus.java
  queue/src/main/java/com/bobjool/queue/domain/util/RedisKeyUtil.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisInitializer.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisPubSubConfig.java
  queue/src/main/java/com/bobjool/queue/presentation/controller/QueueController.java
Labels: 기능

#82 Feat/reservation-feign client
  .github/workflows/run-test.yml
  config/src/main/resources/config-repo/reservation-service.yml
  config/src/main/resources/config-repo/restaurant-service.yml
  reservation/build.gradle
  reservation/http/reservation.http
  reservation/src/main/java/com/bobjool/reservation/ReservationApplication.java
  reservation/src/main/java/com/bobjool/reservation/application/client/RestaurantScheduleClient.java
  reservation/src/main/java/com/bobjool/reservation/application/client/RestaurantScheduleResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/client/RestaurantScheduleReserveReqDto.java
  reservation/src/main/java/com/bobjool/reservation/application/exception/PaymentExceptionHandler.java
  reservation/src/main/java/com/bobjool/reservation/application/exception/ReservationExceptionHandler.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/infra/client/RestaurantScheduleClientImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/messaging/EventSerializer.java
  reservation/src/main/java/com/bobjool/reservation/infra/messaging/ReservationProducer.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  restaurant/http/restaurant-schedule.http
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/restaurantSchedule/RestaurantScheduleController.java
  restaurant/src/main/resources/application-dev.yml
Labels: 기능

#92 Feat/gateway 구현
  auth/build.gradle
  auth/src/main/java/com/bobjool/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/java/com/bobjool/infrastructure/security/JwtUtilImpl.java
  auth/src/main/java/com/bobjool/infrastructure/security/WebSecurityConfig.java
  auth/src/main/resources/application-dev.yml
  config/src/main/resources/config-repo/auth-service.yml
  gateway/build.gradle
  gateway/src/main/java/com/bobjool/gateway/CustomPostFilter.java
  gateway/src/main/java/com/bobjool/gateway/CustomPreFilter.java
  gateway/src/main/java/com/bobjool/gateway/ExcludedPaths.java
  gateway/src/main/java/com/bobjool/gateway/exception/ErrorCode.java
  gateway/src/main/java/com/bobjool/gateway/exception/GlobalExceptionHandler.java
  gateway/src/main/java/com/bobjool/gateway/exception/TokenException.java
  gateway/src/main/java/com/bobjool/gateway/infrastructure/jwt/RedisService.java
  gateway/src/main/java/com/bobjool/gateway/infrastructure/jwt/TokenParser.java
  gateway/src/main/java/com/bobjool/gateway/infrastructure/redis/RedisConfig.java
  gateway/src/main/java/com/bobjool/gateway/presentation/ApiResponse.java
  gateway/src/main/java/com/bobjool/gateway/presentation/SuccessCode.java
  gateway/src/main/resources/application-dev.yml
Labels: 기능

#93 Feat/restaurant search feat
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantContactResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/exception/RestaurantExceptionHandler.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurant/RestaurantService.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurant/RestaurantCategory.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/entity/restaurant/RestaurantRegion.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurant/RestaurantRepositoryCustom.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurant/RestaurantRepositoryCustomImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/restaurant/RestaurantController.java
Labels: 기능

#95 Feat/notification - kafka 메시지 수신
  notification/build.gradle
  notification/http/template.http
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationType.java
  notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/messaging/KafkaConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/template/TemplateMappingConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
  notification/src/main/resources/application-dev.yml
Labels: 기능

#96 Feat/payment timeout redis
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  config/src/main/resources/config-repo/payment-service.yml
  payment/build.gradle
  payment/http/payment.http
  payment/src/main/java/com/bobjool/payment/application/events/PaymentTimeoutEvent.java
  payment/src/main/java/com/bobjool/payment/application/events/ReservationCreatedEvent.java
  payment/src/main/java/com/bobjool/payment/application/service/PaymentService.java
  payment/src/main/java/com/bobjool/payment/domain/enums/PaymentTopic.java
  payment/src/main/java/com/bobjool/payment/infra/messaging/PaymentConsumer.java
  payment/src/main/java/com/bobjool/payment/infra/redis/RedisConfig.java
  payment/src/main/java/com/bobjool/payment/infra/redis/RedisExpirationListener.java
  payment/src/main/java/com/bobjool/payment/infra/redis/RedisInitializer.java
  payment/src/test/java/com/bobjool/payment/EmbeddedRedisConfig.java
  payment/src/test/java/com/bobjool/payment/application/service/PaymentServiceTest.java
  payment/src/test/java/com/bobjool/payment/domain/repository/PaymentRepositoryTest.java
  payment/src/test/resources/application-test.yml
  reservation/http/reservation.http
  reservation/src/main/java/com/bobjool/reservation/application/events/PaymentTimeoutEvent.java
  reservation/src/main/java/com/bobjool/reservation/application/events/ReservationCreatedEvent.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/infra/messaging/ReservationConsumer.java
  restaurant/http/restaurant-schedule.http
Labels: 기능

#103 Feat/notification - 알림 히스토리 API #102
  notification/http/notification.http
  notification/http/template.http
  notification/src/main/java/com/bobjool/notification/application/dto/NotificationHistoryDto.java
  notification/src/main/java/com/bobjool/notification/application/dto/NotificationSearchDto.java
  notification/src/main/java/com/bobjool/notification/application/service/NotificationService.java
  notification/src/main/java/com/bobjool/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/NotificationRepositoryCustom.java
  notification/src/main/java/com/bobjool/notification/infrastructure/repository/NotificationRepositoryCustomImpl.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/NotificationController.java
  notification/src/main/java/com/bobjool/notification/presentation/request/NotificationSearchReqDto.java
  notification/src/main/java/com/bobjool/notification/presentation/response/NotificationSearchResDto.java
  notification/src/main/resources/application-dev.yml
Labels: 기능

#100 [reservation] feat/reservation-role-check #99
  auth/http/auth.http
  auth/src/main/generated/com/bobjool/domain/entity/QUser.java
  auth/src/main/java/com/bobjool/infrastructure/security/WebSecurityConfig.java
  auth/src/main/resources/application-dev.yml
  build.gradle
  config/src/main/resources/config-repo/auth-service.yml
  init.sql
  reservation/http/reservation.http
  reservation/src/main/java/com/bobjool/reservation/application/client/restaurant/RestaurantClient.java
  reservation/src/main/java/com/bobjool/reservation/application/client/restaurant/RestaurantResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/client/restaurantschedule/RestaurantScheduleClient.java
  reservation/src/main/java/com/bobjool/reservation/application/client/restaurantschedule/RestaurantScheduleResDto.java
  reservation/src/main/java/com/bobjool/reservation/application/client/restaurantschedule/RestaurantScheduleReserveReqDto.java
  reservation/src/main/java/com/bobjool/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/bobjool/reservation/infra/aspect/RoleCheckAspect.java
  reservation/src/main/java/com/bobjool/reservation/infra/client/RestaurantClientImpl.java
  reservation/src/main/java/com/bobjool/reservation/infra/client/RestaurantScheduleClientImpl.java
  reservation/src/main/java/com/bobjool/reservation/presentation/controller/ReservationController.java
  reservation/src/test/java/com/bobjool/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/bobjool/reservation/presentation/controller/ReservationControllerTest.java
  restaurant/http/restaurant-schedule.http
Labels: 기능

#104 [Auth] feat/auth-dev #101
  auth/src/main/java/com/bobjool/AuthApplication.java
  auth/src/main/java/com/bobjool/application/client/NotificationClient.java
  auth/src/main/java/com/bobjool/application/dto/SignInResDto.java
  auth/src/main/java/com/bobjool/application/dto/UpdateUserResDto.java
  auth/src/main/java/com/bobjool/application/dto/UserContactResDto.java
  auth/src/main/java/com/bobjool/application/dto/UserResDto.java
  auth/src/main/java/com/bobjool/application/interfaces/JwtUtil.java
  auth/src/main/java/com/bobjool/application/service/AuthService.java
  auth/src/main/java/com/bobjool/application/service/UserService.java
  auth/src/main/java/com/bobjool/infrastructure/client/NotificationClientImpl.java
  auth/src/main/java/com/bobjool/presentation/controller/AuthController.java
  auth/src/main/java/com/bobjool/presentation/controller/UserController.java
  config/src/main/resources/config-repo/auth-service.yml
Labels: 기능

#109 Feat/queue redis
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  queue/build.gradle
  queue/src/main/java/com/bobjool/queue/application/dto/UserQueueData.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisQueueService.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/RedissonLock.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/RedissonLockAspect.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedissonConfig.java
  queue/src/test/java/com/bobjool/queue/presentation/controller/QueueControllerTest.java
  queue/src/test/resources/application-test.yml
Labels: 기능, 리팩토링

#106 Refactor/restaurant schedule authorization processing
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  config/src/main/resources/config-repo/restaurant-service.yml
  restaurant/build.gradle
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantContactResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantForCustomerResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantForMasterResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantUpdateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleUpdateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurant/RestaurantService.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurantSchedule/RestaurantScheduleService.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/repository/RestaurantRepository.java
  restaurant/src/main/java/com/bobjool/restaurant/domain/repository/RestaurantScheduleRepository.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/aspect/RequestLoggingAspect.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/aspect/RequireRole.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/aspect/RoleCheckAspect.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/config/aop/AopConfig.java
  restaurant/src/main/java/com/bobjool/restaurant/infrastructure/repository/restaurant/RestaurantRepositoryCustomImpl.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/restaurant/RestaurantController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/restaurantSchedule/RestaurantScheduleController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleCreateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleUpdateReqDto.java
Labels: 리팩토링

#116 Fix/Notification - 카프카 숫자 데이터 변환 로직, 프로세스 더미 로직 추가 #115
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
Labels: 버그

#117 Fix/Notification - Json 문자열 형태 불일치 이슈 해결 #115
  notification/http/template-backdata.http
  notification/http/template.http
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/Notification.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/messaging/KafkaConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/EventSerializer.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
Labels: 리팩토링

#119 Feat/Queue -http
  queue/http/queue.http
  queue/src/main/java/com/bobjool/queue/application/service/QueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisQueueService.java
  queue/src/main/java/com/bobjool/queue/presentation/controller/QueueController.java
Labels: 문서, 리팩토링, 테스트

#120 Fix/Auth-slack_email은 null일시 중복 검사에서 제외
  auth/src/main/java/com/bobjool/application/service/ValidationService.java
Labels: 리팩토링

#122 Refactor/notification - Map 변환 방어로직 추가 #115
  notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
Labels: 리팩토링

#121 Feat/Auth - .http 테스트 코드 작성하였습니다.
  auth/http/auth.http
  auth/src/main/java/com/bobjool/application/dto/UserContactResDto.java
  auth/src/main/java/com/bobjool/application/dto/UserResDto.java
Labels: 테스트

#124 feat/restaurant - 사용 될 Feign 기능 추가
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantCheckOwnerDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantCheckValidDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantContactResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantForMasterResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurant/RestaurantValidResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleCreateDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleForCustomerResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/dto/restaurantSchedule/RestaurantScheduleResDto.java
  restaurant/src/main/java/com/bobjool/restaurant/application/service/restaurant/RestaurantService.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/api/restaurant/RestaurantController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/controller/api/restaurantSchedule/RestaurantScheduleController.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurant/RestaurantCheckOwnerReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurant/RestaurantCheckValidReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurant/RestaurantCreateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurant/RestaurantUpdateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleCreateReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleReserveReqDto.java
  restaurant/src/main/java/com/bobjool/restaurant/presentation/dto/restaurantSchedule/RestaurantScheduleUpdateReqDto.java
Labels: 기능

#126 feat/Auth-시큐리티 설정 변경
  auth/src/main/java/com/bobjool/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/java/com/bobjool/infrastructure/security/WebSecurityConfig.java
  auth/src/main/java/com/bobjool/presentation/controller/UserController.java
Labels: 설정

#127 Refactor/notification - 리팩토링
  build.gradle
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  config/src/main/resources/config-repo/notification-service.yml
  notification/build.gradle
  notification/http/template-backdata.http
  notification/src/main/java/com/bobjool/notification/application/dto/NotificationDto.java
  notification/src/main/java/com/bobjool/notification/application/factory/NotificationDetailsFactory.java
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/application/service/HistoryService.java
  notification/src/main/java/com/bobjool/notification/application/service/MessagingService.java
  notification/src/main/java/com/bobjool/notification/application/service/SlackService.java
  notification/src/main/java/com/bobjool/notification/application/service/TemplateService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/BobjoolServiceType.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationChannel.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationStatus.java
  notification/src/main/java/com/bobjool/notification/domain/entity/NotificationType.java
  notification/src/main/java/com/bobjool/notification/domain/entity/TemplateContactField.java
  notification/src/main/java/com/bobjool/notification/domain/service/NotificationDetails.java
  notification/src/main/java/com/bobjool/notification/domain/service/TemplateConvertService.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/template/TemplateMappingConfig.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/HistoryController.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/MessagingController.java
  notification/src/main/resources/application-dev.yml
Labels: 리팩토링

#130 Feat/notification - 이메일 전송 기능 구현
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  config/src/main/resources/config-repo/notification-service.yml
  notification/build.gradle
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/application/service/MailService.java
  notification/src/main/java/com/bobjool/notification/application/service/MessagingService.java
  notification/src/main/java/com/bobjool/notification/domain/service/NotificationDetails.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/mail/MailConfig.java
  notification/src/main/java/com/bobjool/notification/presentation/controller/MessagingController.java
Labels: 기능

#139 Feat/queue streams
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  config/src/main/resources/config-repo/queue-service.yml
  queue/build.gradle
  queue/src/main/java/com/bobjool/queue/QueueApplication.java
  queue/src/main/java/com/bobjool/queue/application/client/RestaurantClient.java
  queue/src/main/java/com/bobjool/queue/application/dto/RestaurantCheckOwnerReqDto.java
  queue/src/main/java/com/bobjool/queue/application/dto/RestaurantCheckValidReqDto.java
  queue/src/main/java/com/bobjool/queue/application/dto/RestaurantValidResDto.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessagePublisher.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueMessageSubscriber.java
  queue/src/main/java/com/bobjool/queue/application/service/QueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisQueueService.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisStreamConsumer.java
  queue/src/main/java/com/bobjool/queue/application/service/RedisStreamProducer.java
  queue/src/main/java/com/bobjool/queue/domain/enums/CancelType.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/AopForTransaction.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/CustomSpringELParser.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/RedissonLock.java
  queue/src/main/java/com/bobjool/queue/infrastructure/aspect/RedissonLockAspect.java
  queue/src/main/java/com/bobjool/queue/infrastructure/client/RestaurantClientImpl.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/aop/AopConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisPubSubConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedisStreamConfig.java
  queue/src/main/java/com/bobjool/queue/infrastructure/config/redis/RedissonConfig.java
  queue/src/main/java/com/bobjool/queue/presentation/controller/QueueController.java
Labels: 버그, 기능, 리팩토링, 설정

#155 feat/Auth - 리프레시 토큰 구현
  auth/src/main/java/com/bobjool/application/dto/SignInResDto.java
  auth/src/main/java/com/bobjool/application/dto/TokensResDto.java
  auth/src/main/java/com/bobjool/application/interfaces/JwtUtil.java
  auth/src/main/java/com/bobjool/application/service/AuthService.java
  auth/src/main/java/com/bobjool/application/service/JwtBlacklistService.java
  auth/src/main/java/com/bobjool/infrastructure/security/JwtUtilImpl.java
  auth/src/main/java/com/bobjool/presentation/controller/AuthController.java
  auth/src/test/java/com/bobjool/auth/application/service/AuthServiceTest.java
  auth/src/test/java/com/bobjool/auth/application/service/JwtBlacklistServiceTest.java
  common/src/main/java/com/bobjool/common/exception/ErrorCode.java
  config/src/main/resources/config-repo/auth-service.yml
  gateway/src/main/java/com/bobjool/gateway/ExcludedPaths.java
  gateway/src/main/java/com/bobjool/gateway/infrastructure/jwt/RedisService.java
  gateway/src/main/java/com/bobjool/gateway/infrastructure/jwt/TokenParser.java
Labels: 문서, 기능

#184 Feat/notification - 서킷 브레이커 적용 및 알림 발송 상태 히스토리 반영
  config/src/main/resources/config-repo/notification-service.yml
  notification/build.gradle
  notification/src/main/java/com/bobjool/notification/application/service/EventService.java
  notification/src/main/java/com/bobjool/notification/application/service/HistoryService.java
  notification/src/main/java/com/bobjool/notification/application/service/MessagingService.java
  notification/src/main/java/com/bobjool/notification/application/service/TemplateService.java
  notification/src/main/java/com/bobjool/notification/domain/entity/Notification.java
  notification/src/main/java/com/bobjool/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/bobjool/notification/infrastructure/config/circuit/CircuitBreakerConsumerConfiguration.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/KafkaManager.java
  notification/src/main/java/com/bobjool/notification/infrastructure/messaging/NotificationListener.java
Labels: 기능
